package edu.clarkson.gdc.dashboard.domain.entity;

public enum HistoryType {
	MACHINE_CPU, MACHINE_MEMORY, MACHINE_VMCOUNT, 
	UPS_POWER, UPS_VOLTAGE, UPS_TEMPERATURE, 
	POWER_INPUT_I, POWER_BTY_I, POWER_INVRT_I, POWER_BTY_V, POWER_CHARGE,
	DC_CONSUMPTION
}
