/* Generated By:JavaCC: Do not edit this line. ParamParserConstants.java */
package edu.clarkson.gdc.workflow.param;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParamParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONTEXT = 5;
  /** RegularExpression Id. */
  int INPUT = 6;
  /** RegularExpression Id. */
  int RETURN = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int NUM = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"context\"",
    "\"input\"",
    "\"return\"",
    "<ID>",
    "<NUM>",
    "\",\"",
    "\"|\"",
    "\":\"",
  };

}
